##### Файл тестовых запросов к контролеру users
##### Запросы выполняются с помощью расширения REST Client для VS Code ( https://marketplace.visualstudio.com/items?itemName=humao.rest-client )

##### Регистрация пользователя

POST http://localhost:5001/users/register HTTP/1.1
content-type: application/json

{
    "email": "admin@example.com",
    "password": "hello321qwe",
    "username": "admin"
}

##### Регистрация еще одного пользователя

POST http://localhost:5001/users/register HTTP/1.1
content-type: application/json

{
    "email": "test@inbox.ru",
    "password": "helloworld",
    "username": "user"
}


##### Аутентификация пользователя

POST http://localhost:5001/users/login HTTP/1.1
content-type: application/json

{
    "email": "admin@example.com",
    "password": "hello321qwe"
}

##### Запрос данных пользователя

GET http://localhost:5001/users/me HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjhkODNjNmU1LTZmNmEtNDk4NS1iZjgzLTA4NjYxYWU3N2E0OCIsInJlZ2lzdHJhdGlvbkRhdGUiOiIyMDI0LTA4LTE3VDE5OjU4OjMwLjYyNFoiLCJpYXQiOjE3MjM5MjUzNzAsImV4cCI6MTcyMzk2MTM3MH0.RglMpeWq5iEZGZOW6v4KTXw_DM8LY5mMIVWBcQEPaT8

#### Запрос на изменение роли пользователя

PUT http://localhost:5001/users/0d2e804d-de3a-4dd6-8009-5642eee93b35/role HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjhkODNjNmU1LTZmNmEtNDk4NS1iZjgzLTA4NjYxYWU3N2E0OCIsInJlZ2lzdHJhdGlvbkRhdGUiOiIyMDI0LTA4LTE3VDE5OjU4OjMwLjYyNFoiLCJpYXQiOjE3MjM5MjUzNzAsImV4cCI6MTcyMzk2MTM3MH0.RglMpeWq5iEZGZOW6v4KTXw_DM8LY5mMIVWBcQEPaT8

