##### Файл тестовых запросов к контролеру users
##### Запросы выполняются с помощью расширения REST Client для VS Code ( https://marketplace.visualstudio.com/items?itemName=humao.rest-client )

##### Регистрация пользователя

POST http://localhost:7000/users/register HTTP/1.1
content-type: application/json

{
    "email": "anton.ivanov.hh@gmail.com",
    "password": "hello321qwe",
    "username": "Anton"
}


##### Аутентификация пользователя

POST http://localhost:7000/users/login HTTP/1.1
content-type: application/json

{
    "email": "anton.ivanov.hh@gmail.com",
    "password": "hello321qwe"
}

##### Запрос данных пользователя

GET http://localhost:7000/users/me HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6Ijk2ZTI2NmY4LTIxYTktNDc2ZS05MzdkLTIzNWY1YTFjYjQ0YSIsImlzQWRtaW4iOmZhbHNlLCJlbWFpbCI6ImFudG9uLml2YW5vdi5oaEBnbWFpbC5jb20iLCJyZWdpc3RyYXRpb25EYXRlIjoiMjAyNC0wOC0xNFQxNzo1NDowNy4yMzlaIiwiaWF0IjoxNzIzNjU5Njg5LCJleHAiOjE3MjM2OTU2ODl9.EdTVlnKxdIT35tws3Jno0gkMMPk6C224wDLEwOe87ms

